In [82]:
import numpy as np

with open("data.txt", "r") as r: 
    data = [p for p in r.readlines()]

sequence = [int(p) for p in data[0].split(",")]
boards = []
for i in range(2,len(sequence), 6):
    board = [[[int(elem) for elem in row.split(" ") if elem  != ""] for row in data[i:i+5]]]
    if len(board[0]) > 0:
        boards += board
boards = np.array(boards)

In [94]:
# part 1
bool_boards = np.full((3, 5, 5), False)
for num in sequence:
    bool_boards |= (boards == num)
    ax_1, ax_2 = bool_boards.sum(axis=1), bool_boards.sum(axis=2)
    if (5 in ax_1) | (5 in ax_2):
        break
num * boards[bool_boards].sum()

9864

In [106]:
# part 2
ax_2, ax_2.argmax(axis=1)

(array([[3, 4, 4, 1, 0],
        [2, 3, 2, 3, 2],
        [5, 1, 1, 2, 3]]),
 array([1, 1, 0], dtype=int64))

In [71]:
test_board = np.full((3, 5, 5), True)

In [76]:
test_board.sum(axis=1), test_board.sum(axis=2)

(array([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]),
 array([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]))